// <auto-generated />
namespace ProjetoBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m13));
        
        string IMigrationMetadata.Id
        {
            get { return "201811052035481_m13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
